---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - handsongroup.handson.com
  resources:
  - helloworlds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - handsongroup.handson.com
  resources:
  - helloworlds/finalizers
  verbs:
  - update
- apiGroups:
  - handsongroup.handson.com
  resources:
  - helloworlds/status
  verbs:
  - get
  - patch
  - update
